name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macOS-12

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

        # todo: set language for typo check
      # - name: Check typos
      #   if: matrix.os == 'ubuntu-22.04'
      #   uses: crate-ci/typos@master

      - name: Check formatting, linting, license headers, types and run tests
        run: deno task ok
      
      - name: Create embeddings
        env:
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: deno task create-embeddings
          # |
          # '[ main = "$GITHUB_REF" ] && export PROD="--prod"' \
          # export LOG_FILE="$(mktemp)" \
          # deno task create-embeddings | tee "${LOG_FILE}"

      - name: Create lcov file
        run: deno task cov

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.os }}
          files: cov.lcov